#837 Поправил преобразование из MBR в GPT разметки диска. Доработал добавление 4ого раздела для системного диска

diff --git a/src/Core/System/RootFS/sbin/pbx_firmware b/src/Core/System/RootFS/sbin/pbx_firmware
--- a/src/Core/System/RootFS/sbin/pbx_firmware
+++ b/src/Core/System/RootFS/sbin/pbx_firmware
@@ -109,6 +109,20 @@ fi
 
 # Inform the user of the installation process
 if [ -r "${img_file}" ]; then
+  if command -v gdisk > /dev/null 2>&1; then
+    PARTITION_TYPE=$(/sbin/parted "$DISK" print | grep "Partition Table" | awk '{print $3}')
+    echo " - Performing an action for the msdos section"
+    if [ "$PARTITION_TYPE" == "msdos" ]; then
+      echo -e "w\nY\n" | gdisk "/dev/${systemDevice}" > /dev/null 2>&1;
+      resultGDisk="$?";
+      if [ "$resultGDisk" -eq 0 ]; then
+        echo " - The conversion to GPT has been completed successfully."
+      else
+        echo " - Error converting to GPT."
+      fi
+    fi
+  fi
+
   echo " - Installing new image on /dev/${systemDevice}"
   # Use pv to monitor the progress of the data being piped to the dd command
    if test -w /dev/ttyS0 && ! /bin/busybox setserial -g /dev/ttyS0 | /bin/grep -q unknown; then
